### ISSUE TITLE
Tip: how to get apk-parser to work on 64-bit Ubuntu (newer versions)

### ISSUE THREAD

**Issue by afollestad** [rubenv/node-apk-parser#11]
The newer versions of Ubuntu and Ubuntu server don't support x86 executables.

It can be enabled with this answer on StackOverflow, which should probably be detailed in the README of this project and on the NPM page: http://stackoverflow.com/a/19524010/309644

**This is required to get aapt to run at all, otherwise errors are thrown when apk-parser attempts to spawn aapt.**

**Comment by rubenv** [comment]
Good point. Could you send a pull request with updates to README?

**Comment by afollestad** [comment]
Of course, submitted
