### ISSUE TITLE
Buffer should be bigger

### ISSUE THREAD

**Issue by gergelyke** [rubenv/node-apk-parser#3]
1024*1024 is not always enough. It would be nice to have an option what can be passed in, or just simple make it larger.

**Comment by msalahat** [comment]
I have created a pull request here with patch that has maxBuffer as configuration option that you can specify when calling the parser
https://github.com/rubenv/node-apk-parser/pull/5
Once approved you can call the parse as below
parseApk(FILE_PATH ,  MAX_BUFFER ,CALLBACK );
Or you can use my fork here
https://github.com/msalahat/node-apk-parser/

**Comment by gergelyke** [comment]
Thanks @msalahat ! In the meantime I forked as well :)

https://github.com/gergelyke/node-apk-parser2

**Comment by rubenv** [comment]
@gergelyke please send fixes back as pull requests

**Comment by rubenv** [comment]
Published version 0.1.1 to npm

**Comment by gergelyke** [comment]
Will do - I thought the repo is dead, as I got no response

**Comment by rubenv** [comment]
Might have missed that mail. I think I was on a vacation then. Never hurts to ping a second time.

Do note that I don't blindly implement every feature request (I'm not getting paid for that), but I happily review pull requests.

**Comment by rubenv** [comment]
Anyway, thanks a lot for the patch @msalahat!

**Comment by gergelyke** [comment]
No worries, I only needed that for a prototype - also, I am putting a deprecation notice on the fork, pointing it to here.

**Comment by msalahat** [comment]
@rubenv  You are welcome :)
