### ISSUE TITLE
no unzip command on ubuntu

### ISSUE THREAD

**Issue by CesarTrigo** [rubenv/node-apk-parser#6]
> apk-parser@0.1.3 install /var/www/applivery/node_modules/apk-parser
> node install.js

/var/www/applivery/node_modules/apk-parser/install.js:33
                        throw err;
                              ^
Error: Command failed: /bin/sh: 1: unzip: not found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

npm ERR! apk-parser@0.1.3 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the apk-parser@0.1.3 install script.
npm ERR! This is most likely a problem with the apk-parser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls apk-parser
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/root/devenv/node/bin/node" "/root/devenv/node/bin/npm" "install" "apk-parser"
npm ERR! cwd /var/www/applivery
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by rubenv** [comment]
You need to `apt-get install` it.

**Comment by CesarTrigo** [comment]
I think unzip is not available on apt-get for ubuntu 14-04

**Comment by rubenv** [comment]
It should be there: http://packages.ubuntu.com/search?keywords=unzip&searchon=names&suite=trusty&section=all

**Comment by CesarTrigo** [comment]
Thanks rubenv, Im gonna try!
